CREATE TABLE Utilisateur (
	idU INTEGER NOT NULL AUTO_INCREMENT,
	email VARCHAR(100) NOT NULL,
	mdpU VARCHAR(30) NOT NULL,
	pseudo VARCHAR(50),
	nomU VARCHAR(50),
	prenomU VARCHAR(50),
	PRIMARY KEY (idU),
	UNIQUE KEY (pseudo)
);

CREATE TABLE Artiste (
	idArt INTEGER NOT NULL AUTO_INCREMENT,
	nomArt VARCHAR(50),
	prenomArt VARCHAR(50),
	anneeNaiss INTEGER(4),
	biographie VARCHAR(500),
	PRIMARY KEY (idArt)
);

CREATE TABLE Administrateur (
	idA INTEGER NOT NULL AUTO_INCREMENT,
	emailAdmin VARCHAR(100) NOT NULL,
	mdpAdmin VARCHAR(30) NOT NULL,
	PRIMARY KEY (idA)
);

CREATE TABLE Album (
	idAl INTEGER NOT NULL AUTO_INCREMENT,
	idArt  INTEGER NOT NULL,
	nomAl VARCHAR(70) NOT NULL, 
	dateAl DATE,
	genre VARCHAR(50),
	note INTEGER(2) DEFAULT NULL,
	PRIMARY KEY (idAl),
	FOREIGN KEY (idArt) REFERENCES Artiste (idArt)
);

CREATE TABLE Note (
	idN INTEGER NOT NULL AUTO_INCREMENT,
	idAl INTEGER,
	idU INTEGER,
	note INTEGER DEFAULT NULL,
	PRIMARY KEY (idN),
	FOREIGN KEY (idAl) REFERENCES Album (idAl),
	FOREIGN KEY (idU) REFERENCES Artiste (idU)
);

CREATE TABLE Commentaire (
	idC INTEGER NOT NULL AUTO_INCREMENT,
	idAl INTEGER,
	idU INTEGER,
	commentaire VARCHAR(250),
	PRIMARY KEY (idC),
	FOREIGN KEY (idAl) REFERENCES Album (idAl),
	FOREIGN KEY (idU) REFERENCES Artiste (idU)
);


	